apiVersion: apps/v1

kind: Deployment

metadata:
  name: api-node-surfer

spec:
  replicas: 1

  selector:
    matchLabels:
      app: api-node-surfer

  template:
    metadata:
      labels:
        app: api-node-surfer

    spec:
      containers:
        - name: api-node-surfer

          image: api-node-surfer:latest
          ports:
            - containerPort: 3000
          resources:
            limits:
              cpu: '1'
              memory: '512Mi'
            requests:
              cpu: '0.5'
              memory: '256Mi'

