apiVersion: v1

kind: Service

metadata:
  name: api-node-surfer-service

spec:
  selector:
    app: api-node-surfer

  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: NodePort
